FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY . .
RUN dotnet restore TestWorkindForEducation/TestWorkindForEducation.csproj
RUN dotnet publish TestWorkindForEducation/TestWorkindForEducation.csproj -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app/publish .
EXPOSE 8080
# Ждем 30 секунд чтобы БД точно запустилась
CMD sleep 30 && dotnet TestWorkindForEducation.dll
